name: aottke
favicon: null
layout_spectrum: 0.9526418154127896
typography_spectrum: 1
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#0a0a13'
    - '#708f98'
    - '#414465'
    - '#fec468'
    - '#d4711d'
  brandStrength: 0.125
  lightness: 0.75
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
