name: aottke
favicon: null
layout_spectrum: 0.9526418154127896
typography_spectrum: 1
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f8f9fd'
    - '#307ab5'
    - '#86b6dc'
    - '#363f50'
    - '#c28e80'
  brandStrength: 0.3125
  lightness: 0.6875
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
